### ISSUE TITLE
Request: 2922 Adalogger FeatherWing - RTC + SD Add-on

### ISSUE THREAD

**Issue by arpaterson** [adafruit/Adafruit_CAD_Parts#102]
Request: 
2922 Adalogger FeatherWing - RTC + SD Add-on
cad model

One more request from the big bunch of feather stuff I purchased.

**Comment by djecken** [comment]
Thanks for your request! Just added this one to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/2922%20FeatherWing%20Adalogger
