### ISSUE TITLE
Request - 5626 PCA9548 STEMMA mux

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#104]
hihi! please add the PCA9548 STEMMA mux (https://github.com/adafruit/Adafruit-PCA9548-PCB)

**Comment by djecken** [comment]
Thanks! Part has been added to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5626%20PCA9548%20Stemma
