### ISSUE TITLE
Part request (PID 5639) Adafruit High Power Infrared LED Emitter

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#108]
hihi! please add the Adafruit High Power Infrared LED Emitter (PID 5639) PCB files: https://github.com/adafruit/Adafruit-High-Power-Infrared-LED-Emitter-PCB

**Comment by djecken** [comment]
Thank you, added to the repo. Also added a link to the download page in the product learn guide
