### ISSUE TITLE
Part request (PID 1304) MicroLipo v2

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#109]
hihi! please add the microlipo v2 (PID 1304). PCB files: https://github.com/adafruit/Adafruit-MicroLipo-PCB

**Comment by djecken** [comment]
Thank you. Part has been added to the repo. Also added link to the downloads page in the product guide https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/1304%20MicroLipo%20Charger
