### ISSUE TITLE
Request: NeoPixel Driver BFF

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#110]
hihi! please add the NeoPixel Driver BFF (PID 5645). PCB files: https://github.com/adafruit/Adafruit-NeoPixel-Driver-BFF-PCB

**Comment by djecken** [comment]
Thanks! @BlitzCityDIY Added part to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5645%20NeoPixel%20Driver%20BFF
