### ISSUE TITLE
Request: NeoPixel Grid BFF

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#111]
hihi! please add the 5x5 NeoPixel Grid BFF (PID 5646). PCB files: https://github.com/adafruit/Adafruit-5x5-NeoPixel-Grid-BFF-PCB

**Comment by djecken** [comment]
Thanks! @BlitzCityDIY Feel free to add a link to the model set in the learn guide https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5646%20NeoPixel%20Grid%205x5%20BFF
