### ISSUE TITLE
Part Request: 2995 Feather M0 Bluefruit LE

### ISSUE THREAD

**Issue by mdkendall** [adafruit/Adafruit_CAD_Parts#112]
It would be good to get a 3D model of this module, in particular including the mounting holes and connectors. Thanks.
https://www.adafruit.com/product/2995

**Comment by djecken** [comment]
Thanks for your request! Part has been added to the repo. https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/2995%20Feather%20M0%20Bluefruit%20LE
