### ISSUE TITLE
Adafruit QT 3V to 5V Level Booster Breakout - STEMMA QT / Qwiic 5649

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_CAD_Parts#114]
Heya 👋 
Please can we have the Adafruit QT 3V to 5V Level Booster Breakout - STEMMA QT / Qwiic in CAD format, fusion or otherwise, so that I can finish my air-quality sensor in [onshape](https://cad.onshape.com/documents/6c87821c957a9d8f1f2bb01e/w/84e99686c963599ff6743cac/e/9f6058ae018e60be2dd2356c) :)

https://www.adafruit.com/product/5649
https://github.com/adafruit/Adafruit-QT-3V-to-5V-Level-Booster-PCB

Keep up the good work!

**Comment by djecken** [comment]
Thanks for your part request! The model has been added to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5649%203V%20to%205V%20Level%20Booster
