### ISSUE TITLE
No Rush, waiting for the S3 to buy one, but the Reverse TFT S2 Feather please

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_CAD_Parts#117]
Adafruit ESP32-S2 Reverse TFT Feather
Product ID: 5345

Saw this on ask an engineer this week, as said not a rush. I'll be waiting for the S3 version to hit UK shores before I buy one, but I'll start integrating the CAD model sooner and sure the footprint will be near identical so thought I'd bung in the request.
Thanks ❤️

**Comment by djecken** [comment]
Thank you for your request! The part has been added to the repo. https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5345%20Feather%20ESP32-S2%20TFT%20Reverse
