### ISSUE TITLE
3133 cad invalid?

### ISSUE THREAD

**Issue by tonysunshine** [adafruit/Adafruit_CAD_Parts#119]
Hi seems like the CAD files for 3133 GPS module are invalid? I tried all 3 - f3d, step, and stl, and all 3 won't open or import into solidworks for fusion

**Comment by djecken** [comment]
Hello! Thanks for posting an issue. I updated the model and re-exported f3d, step and STL. I have verified the step model imports correctly using FreeCAD. I had to download the step file using the "raw" option from github and download as a text file. Using macOS I then had to explicitly change file format from txt to STEP document using the file inspector. Hope that helps!
