### ISSUE TITLE
CAD Request: ID 5395 - QTPy ESP32 PICO

### ISSUE THREAD

**Issue by finger563** [adafruit/Adafruit_CAD_Parts#120]
Right now I'm using the CAD for QTPy ESP32 C3 (5405) which is _very_ similar, but would like to have the actual STEP file for the QTPy ESP32 PICO please :)

**Comment by djecken** [comment]
Thanks for your part request! Files have been added to this repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5395%20QT%20Py%20ESP32%20PICO
