### ISSUE TITLE
Part request: 5405 Adafruit QT Py ESP32-C3 WiFi Dev Board with STEMMA QT

### ISSUE THREAD

**Issue by adamwolf** [adafruit/Adafruit_CAD_Parts#127]
Thanks!

**Comment by djecken** [comment]
Hello, this part is already in the repo, thanks https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5405%20QTPy%20ESP32%20C3

**Comment by adamwolf** [comment]
So sorry!
