### ISSUE TITLE
Ethernet Featherwing - damaged or incomplete 3D files?

### ISSUE THREAD

**Issue by bludin** [adafruit/Adafruit_CAD_Parts#130]
I get errors (unexpected end of file) when I try to open the STEP or STL files of the Ethernet Featherwing 
(https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/3201%20Ethernet%20FeatherWing). I don't have that problem with other 3D files from this repo. Could it be that the files are damaged or incomplete?

**Comment by djecken** [comment]
Verified the STEP file opens properly in FreeCAD and Fusion 360. Try using the "Download raw file" button in the header menu when viewing the step file on GitHub.
