### ISSUE TITLE
Part request: PID 5740 ANO Rotary Encoder STEMMA

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#132]
PCB repo: https://github.com/adafruit/Adafruit-ANO-Rotary-Navigation-Encoder-to-I2C

**Comment by djecken** [comment]
Thanks! Parts added to repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5740%20ANO%20Rotary%20Encoder%20QT
