### ISSUE TITLE
Request: Stereo I2S amp (PID 987)

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#134]
hello! requesting Stereo 3.7W Class D Audio Amplifier - MAX98306 (PID 987). PCB repo: https://github.com/adafruit/Adafruit-MAX98306-Class-D-Amp-PCB

**Comment by djecken** [comment]
Hey thanks for your part request, files have been added https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/987%20MAX98306%20Stereo%20Amp
