### ISSUE TITLE
Part request: 4683/4739 MPM3610 3.3V/5V Buck Converter Breakout - 21V In 3.3V Out at 1.2A

### ISSUE THREAD

**Issue by ernia93** [adafruit/Adafruit_CAD_Parts#135]
Part Request for https://www.adafruit.com/product/4739

**Comment by djecken** [comment]
Thanks for the request, part had been added to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4739%20MPM3610%205V%20Buck
