### ISSUE TITLE
Parts Request: 1264, 1271, 3967, and 5188

### ISSUE THREAD

**Issue by osiengintern** [adafruit/Adafruit_CAD_Parts#136]
Good afternoon,

I was wondering if it was possible to get the CAD files for the following Adafruit components?

https://www.adafruit.com/product/1264
https://www.adafruit.com/product/1271
https://www.adafruit.com/product/3967
https://www.adafruit.com/product/5188

Thank you!

**Comment by osiengintern** [comment]
Good afternoon,

Just wondering if there was an update on these CAD files? Thank you!

**Comment by djecken** [comment]
Hello, thanks for the part request. Files has been added to the repo
