### ISSUE TITLE
Part Request: 4282 Adafruit PiRTC - Precise DS3231 Real Time Clock for Raspberry Pi

### ISSUE THREAD

**Issue by bryan** [adafruit/Adafruit_CAD_Parts#143]
Adafruit PiRTC - Precise DS3231 Real Time Clock for Raspberry Pi
Looking for the model of https://www.adafruit.com/product/4282. 

Thanks.

**Comment by djecken** [comment]
Thanks for the part request, files have been added to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4282%20PiRTC%20DS3231
