### ISSUE TITLE
Part request: 5752 quad rotary encoder

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#144]
https://github.com/adafruit/Adafruit-I2C-Quad-Rotary-Encoder-Breakout-PCB

https://www.adafruit.com/product/5752

**Comment by djecken** [comment]
Thanks! Files have been added to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5752%20Quad%20Rotary%20Breakout
