### ISSUE TITLE
Part Request (PID 1904) MicroLipo MicroUSB

### ISSUE THREAD

**Issue by ondrovic** [adafruit/Adafruit_CAD_Parts#146]
Can you please add MicroUsb MicroLipo (PID 1904). Looks like the PCB files are located here already: https://github.com/adafruit/Adafruit-MicroLipo-PCB

**Comment by djecken** [comment]
Thanks for your part request, files have been added to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/1904%20MicroUSB%20Lipo%20Charger
