### ISSUE TITLE
Cannot open STEP file in Solidworks: 4062 Adafruit Feather nRF52840 Express

### ISSUE THREAD

**Issue by ppddry** [adafruit/Adafruit_CAD_Parts#147]
Cannot open 4062 Adafruit Feather nRF52840 Express STEP file in Solidworks.

**Comment by djecken** [comment]
I verified the 4062 step file opens properly in FreeCAD. Other users have reported similar issues with step files. One thing to try is using the download raw file button, annotated in this screenshot

![raw-file-icon-screenshot](https://github.com/adafruit/Adafruit_CAD_Parts/assets/869133/00377e72-daa2-45cc-8b00-87259f5c2916)
