### ISSUE TITLE
More Parts Request

### ISSUE THREAD

**Issue by whittedb** [adafruit/Adafruit_CAD_Parts#15]
Metro Mini
All form factors of the FX sound board

**Comment by AGenews** [comment]
**3321 Mini Color TFT with Joystick FeatherWing** .... please & Thanks a lot!
Best,
Andreas

**Comment by djecken** [comment]
@AGenews just added 3321 Mini color TFT with Joystick, cheers!

**Comment by AGenews** [comment]
WOW THANKS A LOT!!!

**Comment by djecken** [comment]
Just added 3 audio FX sound boards, cheers! https://github.com/adafruit/Adafruit_CAD_Parts/tree/master/2133%20Audio%20FX%20Soundboard%20with%20Headphone https://github.com/adafruit/Adafruit_CAD_Parts/tree/master/2217%20Adafruit%20FX%20Soundboard%20with%20Amp https://github.com/adafruit/Adafruit_CAD_Parts/tree/master/2341%20Adafruit%20EZ-SFX%20Mini

**Comment by djecken** [comment]
metro mini just added https://github.com/adafruit/Adafruit_CAD_Parts/tree/master/2590%20Metro%20Mini

**Comment by whittedb** [comment]
Awesome!  Thank you.
