### ISSUE TITLE
4062 wrong model step file

### ISSUE THREAD

**Issue by alexfriman** [adafruit/Adafruit_CAD_Parts#153]
Gif file [4062-nRF52830-Feather.gif](https://github.com/adafruit/Adafruit_CAD_Parts/blob/main/4062%20nRF52840%20Feather/4062-nRF52830-Feather.gif) shows a board with an SWD connector, but the step file [4062-nRF52830-Feather.step](https://github.com/adafruit/Adafruit_CAD_Parts/blob/main/4062%20nRF52840%20Feather/4062-nRF52830-Feather.step) has no SWD connector

**Comment by djecken** [comment]
Verified model includes SWD connector using FreeCAD  0.20.1
