### ISSUE TITLE
Model request: 5743 Mini I2C Gamepad with Seesaw 

### ISSUE THREAD

**Issue by benlk** [adafruit/Adafruit_CAD_Parts#154]
This thing: https://www.adafruit.com/product/5743

The closest object already in this repo appears to be https://www.adafruit.com/product/3632 , but that has a different button layout and different dimensions.

**Comment by mikeysklar** [comment]
Another [forum request](https://forums.adafruit.com/viewtopic.php?t=208987) for the Mini I2C Gamepad CAD files.

**Comment by djecken** [comment]
thanks for the request, files for model have been added https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5743%20Mini%20Gamepad%20STEMMA%20QT
