### ISSUE TITLE
3013 DS3231 RTC - Impossible to read STEP and STL files

### ISSUE THREAD

**Issue by cyrilda** [adafruit/Adafruit_CAD_Parts#168]
Hi,
Best wishes for 2024 !
Please find my issue.
Thanks in advance.
Cyril
----------------------------------------------------------------------------------------
WHICH REPO IS CONCERNED ?
3013 DS3231 RTC
https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/3013 DS3231 RTC/
----------------------------------------------------------------------------------------
WHICH FILES ARE CONCERNED ?
STEP file
STL file
----------------------------------------------------------------------------------------
WHAT IS THE PROBLEM ?
error message when I want to open or import these files on Solidworks 2022 
----------------------------------------------------------------------------------------

**Comment by djecken** [comment]
Try download the files by going to the file on github and clicking the "download" button on the right. 
![Screenshot 2024-08-19 at 10 10 41 AM](https://github.com/user-attachments/assets/0d5321bd-8d8d-40e5-a294-81693b999648)
