### ISSUE TITLE
QtPy ESP32-S3 CAD files

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit_CAD_Parts#172]
There are currently five QtPy board CAD files in the repo, but the ESP32-S3 is not present. Please make this available as requested in [this forum thread](https://forums.adafruit.com/viewtopic.php?t=208802).

**Comment by djecken** [comment]
Thanks! CAD files for QT Py ESP32-S3 has been added and linked in the products learn guide  https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5426%20QT%20Py%20ESP32-S3
