### ISSUE TITLE
Part Request: 1119 Tactile Switch (12mm square, 6mm tall)

### ISSUE THREAD

**Issue by afreeland** [adafruit/Adafruit_CAD_Parts#18]
I was hoping to put in a request for this.  This would also be a good one for me to help contribute and add to the library.  I would like to help if there are general guidelines or procedures let me know and I will build it =)

**Comment by djecken** [comment]
Yay, go for it! Part IDs are normally first in the title. Mostly try to supply STEP and STL files. GIF or JPG thumbnail of the model is also nice to have.

**Comment by afreeland** [comment]
Awesome, look forward to building this!  Love what Adafruit does for the maker community and would be glad to help =)
