### ISSUE TITLE
Adafruit Infrared IR Remote Receiver PID 5939

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#181]
https://github.com/adafruit/Adafruit-Infrared-IR-Remote-Receiver-PCB

**Comment by djecken** [comment]
thanks! files for part has been added and linked in the product guide https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5939%20IR%20Remote%20Receiver
