### ISSUE TITLE
Fusion Link : BLE Vibration Bracelet

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit_CAD_Parts#182]
I know this is not the right location, but the right people are here. [Forum user rmnrmnd requested](https://forums.adafruit.com/viewtopic.php?t=211570) the [Fusion 360 CAD files](https://learn.adafruit.com/ble-vibration-bracelet?view=all#powering-3063430) for the BLE Vibration Bracelet project. The link in the guide is no longer valid. Can you post an updated link? I can update the guide.

**Comment by videopixil** [comment]
sweet thanks @mikeysklar fusion updated how directories are linked. I updated the guide to the new link: https://a360.co/3KVBwFe

**Comment by mikeysklar** [comment]
Perfect. Thank you.
