### ISSUE TITLE
Part 815 Servo Driver 16 Channel - Models Corrupt?

### ISSUE THREAD

**Issue by marlauckas** [adafruit/Adafruit_CAD_Parts#184]
815 Servo Driver 16 Channel
Tried uploading/opening in both Fusion360 and FreeCAD.  Both programs are rejecting as 'corrupt'. Thoughts? Thanks!

**Comment by djecken** [comment]
Try download the files by going to the file on github and clicking the "download" button on the right 
![Screenshot 2024-08-19 at 10 06 44 AM](https://github.com/user-attachments/assets/e740f6d0-6228-4803-ba0b-52c3da8e2c9c)
