### ISSUE TITLE
Part Request for: Product ID 2090

### ISSUE THREAD

**Issue by chardane** [adafruit/Adafruit_CAD_Parts#185]
Would be super awesome to get a CAD of this:

2.8" TFT LCD with Cap Touch Breakout Board w/MicroSD Socket - EYESPI Connector
https://www.adafruit.com/product/2090 

Thank you for considering!

**Comment by djecken** [comment]
Hiii! @chardane Thanks for your part request. I was actually going to use this in a future project, so great timing! You can download the models here https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/2090%202.8in%20TFT%20Cap%20Touch
