### ISSUE TITLE
model for ADA# 5978 USB-C Plug Breakout

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit_CAD_Parts#186]
This [variation of the USB-C breakout](https://www.adafruit.com/product/5978) is a newer product in the Adafruit store. Please create a model when possible. 

[Forum request](https://forums.adafruit.com/viewtopic.php?t=212553) thread

**Comment by djecken** [comment]
Thanks for the request, files are available here https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5978%20USB-C%20Plug%20Breakout

**Comment by mikeysklar** [comment]
Thank you. Much appreciated. 

Follow-up question. Is this something I should be doing by open the Eagle BRD file in Fusion 360 and exporting the different formats?
