### ISSUE TITLE
CAD request for 5988 (Adafruit RS-232 Full Pinout Level-Shifter Breakout)

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#188]
https://www.adafruit.com/product/5988

https://github.com/adafruit/Adafruit-RS-232-Level-Shifter-Breakout-PCB

**Comment by djecken** [comment]
thanks for your part request, parts addded to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5988%20RS-232%20Level%20Shifter
