### ISSUE TITLE
Request : DRV8871 CAD ADA# 3390

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit_CAD_Parts#189]
Forum [request](https://forums.adafruit.com/viewtopic.php?t=213574) for [DRV8871 DC Motor breakout](https://www.adafruit.com/product/3190).

**Comment by djecken** [comment]
files for part have been added to the repot. Thanks for posting this request! https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/3190%20DRV8871%20Breakout
