### ISSUE TITLE
CAD request CH334 2-port ADA# 5999

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit_CAD_Parts#190]
[Forum request](https://forums.adafruit.com/viewtopic.php?t=213948) for CAD part [ADA# 5999](https://www.adafruit.com/product/5999)

**Comment by djecken** [comment]
thanks for posting this request. Added files to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5999%20CH334F%202-Port%20HUB
