### ISSUE TITLE
Request: 5708 Adafruit CAN Pal

### ISSUE THREAD

**Issue by danielljeon** [adafruit/Adafruit_CAD_Parts#198]
3D model request for [5708 Adafruit CAN Pal - CAN Bus Transceiver - TJA1051T/3](https://www.adafruit.com/product/5708).

**Comment by djecken** [comment]
Part has been added to the repo. https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5708%20CAN%20Pal Thanks for your request
