### ISSUE TITLE
Requesting model for 3201 Adafruit Ethernet FeatherWing

### ISSUE THREAD

**Issue by TomKeddie** [adafruit/Adafruit_CAD_Parts#21]
Looking to build a carrier for it, need to check clearance etc.

**Comment by djecken** [comment]
Just added this part to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/master/3201%20Ethernet%20FeatherWing

**Comment by TomKeddie** [comment]
Thanks @djecken, stay safe!
