### ISSUE TITLE
Requesting model for 3403 Adafruit Feather M0 Express

### ISSUE THREAD

**Issue by TomKeddie** [adafruit/Adafruit_CAD_Parts#22]
I guess I can use the mode for the M4 but would prefer the real thing.  Thanks.

**Comment by djecken** [comment]
Just added part to the repo, cheers! https://github.com/adafruit/Adafruit_CAD_Parts/tree/master/3403%20Feather%20M0%20Express

**Comment by brysonian** [comment]
It seems to be the wrong size? In Fusion it shows up about 2.5mm too short. I'm uploading the f3d file to my fusion lib.
