### ISSUE TITLE
Incorrect directory name for part 3258

### ISSUE THREAD

**Issue by zencow** [adafruit/Adafruit_CAD_Parts#30]
Hi...

I was looking through the repo and found what I was looking for, but the directory is incorrectly named:
https://github.com/adafruit/Adafruit_CAD_Parts/tree/master/3268%20USB%20Panel%20Mout%20Cable

"3268 USB Panel Mout Cable"
should be
"3258 USB Panel Mount Cable"

The main issue is the part number "3258", but there's also a minor typo if you are able to fix that, too.  The files within the directory appear to be named correctly.

**Comment by djecken** [comment]
Thank you for letting us know! Just updated the directory name.
