### ISSUE TITLE
•	Adafruit ISM330DHCX 6-DOF IMU 3D model

### ISSUE THREAD

**Issue by RKoziolintellisenseinc** [adafruit/Adafruit_CAD_Parts#46]
HI we building system including  •	Adafruit ISM330DHCX 6-DOF IMU. It would bee very valuable for us to have 3D model of this board since we are using 3D CAD. The model could be in STEP, IGES or even  STL format.

All help would be greatly appreciate.

**Comment by djecken** [comment]
added part to repo, thanks https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4502%206DoF%20IMU
