### ISSUE TITLE
Please release individual components like the backplate and the keycap plate for the MacroPad

### ISSUE THREAD

**Issue by back7co** [adafruit/Adafruit_CAD_Parts#54]
Please release the individual component 3D or CAD files for the MacroPad (https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5128%20MacroPad%20RP2040%20Kit)
Releasing the STL of the entire assembled project isn't thoroughly helpful, especially for makers that want to make their own keycap plate or bottom plate.

**Comment by djecken** [comment]
Thanks for the feedback! The MacroPad 2040 kit has been updated with keyplate and bottom plates exported as separate components in STL, STEP and F360 formats.
