### ISSUE TITLE
Part Request: Adafruit Perma-Proto Small Mint Tin Size Breadboard PCB

### ISSUE THREAD

**Issue by chardane** [adafruit/Adafruit_CAD_Parts#58]
https://www.adafruit.com/product/1214

Would be awesome to have, thank you so much!

**Comment by djecken** [comment]
Added part to the repo, thank you https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/1214%20PermaProto%20Small%20Mint

**Comment by chardane** [comment]
Thank you so much!!
