### ISSUE TITLE
Part Request: 5405 Adafruit QT Py ESP32-C3 WiFi Dev Board

### ISSUE THREAD

**Issue by awstanley** [adafruit/Adafruit_CAD_Parts#62]
https://www.adafruit.com/product/5405

I've noticed the dimensions aren't quite the same as the other QT Py boards, and it would be great to have for the purposes of 3D printing cases for it.

Thanks.

**Comment by djecken** [comment]
Part added, thanks https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5405%20QTPy%20ESP32%20C3
