### ISSUE TITLE
 Part Request: 5046 Adafruit BME688 - Temperature, Humidity, Pressure and Gas Sensor - STEMMA QT

### ISSUE THREAD

**Issue by awstanley** [adafruit/Adafruit_CAD_Parts#68]
https://www.adafruit.com/product/5046

I've also noticed the BME680 (https://www.adafruit.com/product/3660) is missing if that helps.

**Comment by djecken** [comment]
BME680 has been added to the repo, thanks! https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/3660%20BME680
