### ISSUE TITLE
Part Request: Adafruit 1.54" Tri-Color eInk 4868

### ISSUE THREAD

**Issue by EinRainerZufall** [adafruit/Adafruit_CAD_Parts#70]
https://www.adafruit.com/product/4868

**Comment by djecken** [comment]
Hello, please consider using the monochrome eink display. It uses the same PCB and components. Thanks! https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4196%201.54in%20eink%20display%20SSD1681
