### ISSUE TITLE
5405 QTPy ESP32 C3

### ISSUE THREAD

**Issue by othersystemnet** [adafruit/Adafruit_CAD_Parts#72]
Hi, (& sorry for my bad english...)
All the 3D files (f3d,stp,stl) for "5405 QTPy ESP32 C3" in "https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5405%20QTPy%20ESP32%20C3" doesn't work. It's possible for you to reupload it ? Thx a lot.

**Comment by djecken** [comment]
Confirmed STEP file opens in FreeCAD 
![qtpy-c3-freecad-step](https://user-images.githubusercontent.com/869133/195916884-742976b9-e3f8-47ef-926c-12b69bea7285.jpg)
