### ISSUE TITLE
Parts Request: Micro-Lipo Charger 4410

### ISSUE THREAD

**Issue by bwolfram1** [adafruit/Adafruit_CAD_Parts#75]
I use these every time for handheld RPis and other boards that dont have a normal jst connector like the Portenta. Can we please get this part? 

https://www.adafruit.com/product/4410

**Comment by djecken** [comment]
Added new part to the repo, thanks for the request! https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4410%20Micro%20Lipo%20USBC
