### ISSUE TITLE
5146 Adafruit 24LC32 I2C EEPROM Breakout

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#81]
hihi @djecken please add PID 5146 (Adafruit 24LC32 I2C EEPROM Breakout)

(https://github.com/adafruit/Adafruit-24LC32-PCB)

**Comment by djecken** [comment]
Thanks! Added part to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5146%2024LC32%20I2C%20EEPROM
