### ISSUE TITLE
5625 Adafruit Qwiic / Stemma QT 5 Port Hub

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#82]
hihi please add PID 5625 (Adafruit Qwiic / Stemma QT 5 Port Hub) when you have a chance

(https://github.com/adafruit/Adafruit-Qwiic-Stemma-QT-5-Port-Hub-PCB)

**Comment by djecken** [comment]
Thanks Liz! Got it added to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5625%20Stemma%205%20Port%20Hub
