### ISSUE TITLE
5423 Adafruit TSC2007 I2C Resistive Touch Screen Controller

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/Adafruit_CAD_Parts#83]
hihi please add PID 5423 (Adafruit TSC2007 I2C Resistive Touch Screen Controller)

(https://github.com/adafruit/Adafruit-TSC2007-PCB)

**Comment by djecken** [comment]
Thanks Liz! Part added https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5423%20TSC2007%20I2C%20Resistive%20Touch
