### ISSUE TITLE
Part request: 2795 Adalogger and 4650 128x64 OLED

### ISSUE THREAD

**Issue by arpaterson** [adafruit/Adafruit_CAD_Parts#85]
Would be nice to add the step files for the feather 32u4 adalogger and 64 line OLED feather wing here.

**Comment by djecken** [comment]
Thanks for your request. The Adalogger has been added. https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/2795%20Feather%2032u4%20Adalogger

Keeping this issue open for 4650 OLED

**Comment by arpaterson** [comment]
Thank you! I can make it a separate issue / will do so for later requests.

**Comment by djecken** [comment]
Thanks, just added 4650 OLED featherwing https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4650%20OLED%20FeatherWing
