### ISSUE TITLE
CAD Request: Metro M4 - 3382

### ISSUE THREAD

**Issue by yashm** [adafruit/Adafruit_CAD_Parts#86]
Hello, Is any CAD available for Metro M4  https://www.adafruit.com/product/3382?
Looking for STEP/IGES.
Thank you!

**Comment by djecken** [comment]
Thanks for your request! Just added the metro m4 to the repo https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/3382%20Metro%20M4
