### ISSUE TITLE
Request: 3231/3232 Feather wing lora RFM95W

### ISSUE THREAD

**Issue by arpaterson** [adafruit/Adafruit_CAD_Parts#91]
Request:
3231 Feather wing lora RFM95W 900MHz
3232 Feather wing lora RFM95W 433MHz

Probably the same model.

**Comment by djecken** [comment]
Thanks! Yes, there's a single model for all radio feather wings https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/3229%20Radio%20FeatherWing
