### ISSUE TITLE
Request: 4646 BNO055 - STEMMA QT / Qwiic

### ISSUE THREAD

**Issue by arpaterson** [adafruit/Adafruit_CAD_Parts#92]
Request:
[Adafruit 9-DOF Absolute Orientation IMU Fusion Breakout - BNO055 - STEMMA QT / Qwiic](https://www.adafruit.com/product/4646)
Cad model.

The one with Quiic!

**Comment by djecken** [comment]
Just added to the repo, thanks!  https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4646%20BNO055%20Stemma
