### ISSUE TITLE
Request: 4565 LSM6DSOX + LIS3MDL FeatherWing - Precision 9-DoF IMU

### ISSUE THREAD

**Issue by arpaterson** [adafruit/Adafruit_CAD_Parts#93]
Request:
4565 LSM6DSOX + LIS3MDL FeatherWing - Precision 9-DoF IMU
cad model.

The feather wing version!

**Comment by djecken** [comment]
Thanks! Part has been added https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4565%20FeatherWing%20LIS3MDL%20LSM6DSOX
