### ISSUE TITLE
Request: 5543 LSM6DS3TR-C + LIS3MDL - Precision 9 DoF IMU - STEMMA QT / Qwiic

### ISSUE THREAD

**Issue by arpaterson** [adafruit/Adafruit_CAD_Parts#94]
Request: 
5543 LSM6DS3TR-C + LIS3MDL - Precision 9 DoF IMU - STEMMA QT / Qwiic
cad model

The little stemma/quiic version!

**Comment by djecken** [comment]
Thanks, part has been added https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5543%20LSM6DS3-LIS3MDL
