### ISSUE TITLE
Request: 4517 LSM6DSOX + LIS3MDL - Precision 9 DoF IMU - STEMMA QT / Qwiic

### ISSUE THREAD

**Issue by arpaterson** [adafruit/Adafruit_CAD_Parts#95]
Request:
4517 LSM6DSOX + LIS3MDL - Precision 9 DoF IMU - STEMMA QT / Qwiic
cad model

Another 9 DoF sensor with quiic!

**Comment by djecken** [comment]
Thanks! Just added this one https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/4517%20LSM6DSOX-LIS3MDL
